# Generated by Django 3.2.4 on 2021-08-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='numHabitacion',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='numPiso',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='registrohuespedes',
            name='numPersonas',
            field=models.IntegerField(default=''),
        ),
    ]
