# Generated by Django 3.2.4 on 2021-08-17 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0002_auto_20210815_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='DesDetallecripcion',
            new_name='Detalle',
        ),
    ]
