# Generated by Django 3.2.4 on 2021-08-17 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0003_rename_desdetallecripcion_pago_detalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrohuespedes',
            name='Habitacion',
        ),
        migrations.AddField(
            model_name='registrohuespedes',
            name='Reserva',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Hotel.reserva'),
        ),
    ]
