# Generated by Django 3.2.4 on 2021-08-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0004_auto_20210817_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='numHabitacion',
            field=models.CharField(default='', max_length=6),
        ),
    ]
