# Generated by Django 3.2.4 on 2021-08-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0005_alter_habitacion_numhabitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='numReserva',
            field=models.CharField(default='', max_length=10),
        ),
    ]
