# Generated by Django 3.2.4 on 2021-08-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0006_reserva_numreserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicios',
            name='Cliente',
        ),
        migrations.RemoveField(
            model_name='servicios',
            name='Estado',
        ),
        migrations.AddField(
            model_name='pago',
            name='Estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado')], default='Pendiente', max_length=30),
        ),
    ]
