# Generated by Django 3.2.4 on 2021-08-18 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0009_pago_numpago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrohuespedes',
            name='numRegistro',
        ),
    ]
