# Generated by Django 3.2.4 on 2021-08-18 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0010_remove_registrohuespedes_numregistro'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='Servicios',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Hotel.servicios'),
        ),
    ]
